// Script to max out hacking XP, because 'weaken' doesn't raise security, this should be faster
node = getHostname();
res = scan(node)
for (i=0; i < res.length; i++)
{
    deep_res = scan(res[i]);
    for(j=0; j < deep_res.length; j++)
    {
        if (!res.includes(deep_res[j]))
        {
            res.push(deep_res[j]);
        }    
    }
}

while (true)
{
    for (i=0; i < res.length; i++)
    {
        if (hasRootAccess(res[i]))
        {
            weaken(res[i]);
        }
    }
}